#!/usr/bin/env bash

set -e

APP_PATH=$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)

APP_RELPATH="${APP_PATH}/../"
APP_FRAMEWORKS="${APP_RELPATH}/Frameworks"
APP_RESOURCES="${APP_RELPATH}/Resources"

export PATH="${APP_PATH}:$PATH"

export LILYPOND_DATADIR="${APP_RESOURCES}/share/lilypond/__LY_VERSION"
export LILYPOND_LOCALEDIR="${APP_RESOURCES}/share/locale"
export LILYPOND_RELOCDIR="${APP_RESOURCES}/etc/relocate"

uuid=$(uuidgen)

${APP_PATH}/lilypond -o /tmp/lilypond.${uuid} - <<EOF
\\version "__LY_VERSION"

\\header{ title = "C Major scale" }
\\relative { c' d e f g a b c }
EOF

rm /tmp/lilypond.${uuid}.pdf

USR_CONFIG=${HOME}/.config/lilypond/lilypond.conf

if [ -f "${USR_CONFIG}" ]; then
    while read var value; do
        export "${var}"="${value}"
    done < "${USR_CONFIG}"
fi

if [ -z ${ly_usr_term+x} ]; then
    ly_usr_term=$(${APP_PATH}/lilypond-dialog)
fi

[ -z "${ly_usr_term}" ] && { exit; }

if [ -f "${ly_usr_term}" ] && [ -x "${ly_usr_term}" ]; then
    if [ ! -f "${USR_CONFIG}" ]; then
        mkdir -p "$(dirname "${USR_CONFIG}")"
    fi

    echo "ly_usr_term ${ly_usr_term}" >> "${USR_CONFIG}"

    bash -c "${ly_usr_term}"
else
    /usr/bin/osascript -e "display notification \
        \"invalid file\" with title \"lilypond\""
fi
